name: Tag Pipeline (Production)

env:
  AWS_REGION: ap-southeast-1
on:
  push:
    tags:
      - 'v*'

jobs:
  tag-version:
    runs-on: ubuntu-latest
    environment: all
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Retag image to Amazon ECR
        env:
          ECR_REPOSITORY: nodejs-tutorialspoint
          IMAGE_TAG_HASH: ${{ github.sha }}
          IMAGE_TAG: ${{ github.ref_name }}
        run: |
          MANIFEST=$(aws ecr batch-get-image --repository-name $ECR_REPOSITORY --image-ids imageTag=$IMAGE_TAG_HASH --output text --query 'images[].imageManifest')
          echo "MANIFEST=$MANIFEST"
          aws ecr put-image --repository-name $ECR_REPOSITORY --image-tag $IMAGE_TAG --image-manifest "$MANIFEST"
          aws ecr describe-images --repository-name $ECR_REPOSITORY --image-ids imageTag=$IMAGE_TAG
